### PR TITLE
Convert to Python3

### PR DESCRIPTION
**Pull request by ralic**
using : find . -name '*.py' | xargs 2to3 -w

### CODE REVIEW

**Review by Duroktar — CHANGES_REQUESTED** [review]
I think 2to3 went a little lisp with the brackets :D

_However_ the change on line 1 to a relative style import may be a good change and if you want to edit out the other 4 and leave just that in I'll gladly accept the pull request. Cheers :beers:

**Comment by ralic** [comment]
Ok, thanks !

**Review by Duroktar — APPROVED** [review]
Looks great! :+1: 

Thank you for contributing!

**Comment by Duroktar** [comment]
P.S. Check out the can-i-haz-files branch for more customization options. (You'll want to link the project dir to ~/.catsass/ if you do, that's where it looks for custom files)

https://github.com/Duroktar/CatsAss/tree/can-i-haz-filez

**Pull request merged**
